# Generated by Django 3.2.6 on 2021-08-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=240, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('child_first_name', models.CharField(max_length=240, verbose_name="Child's First Name")),
                ('child_last_name', models.CharField(max_length=240, verbose_name="Child's Last Name")),
                ('allergies', models.CharField(max_length=240, verbose_name='Allergies')),
            ],
        ),

        ]