# Generated by Django 3.2.6 on 2021-08-07 18:10

from django.db import migrations

def create_data(apps, schema_editor):
    Customers = apps.get_model('customers', 'Customers')
    Customers(first_name="Jamison", last_name="Blackwell", email="blackwellj1040@email.com", child_first_name="Noah", child_last_name="Blackwell", allergies="peanuts").save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),


    ]

    operations = [
        migrations.RunPython(create_data),
    ]